# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from servo_msgs/ServoStateList.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import servo_msgs.msg

class ServoStateList(genpy.Message):
  _md5sum = "9a071e2c8f2c9207110dcfde37177dda"
  _type = "servo_msgs/ServoStateList"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """ServoState[] servo_states
================================================================================
MSG: servo_msgs/ServoState
float64 timestamp   # motor state is at this time
int32 id            # motor id
int32 goal          # commanded position (in encoder units)
int32 position      # current position (in encoder units)
int32 error         # difference between current and goal positions
int32 voltage       # current voltage (mv)
"""
  __slots__ = ['servo_states']
  _slot_types = ['servo_msgs/ServoState[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       servo_states

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ServoStateList, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.servo_states is None:
        self.servo_states = []
    else:
      self.servo_states = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.servo_states)
      buff.write(_struct_I.pack(length))
      for val1 in self.servo_states:
        _x = val1
        buff.write(_get_struct_d5i().pack(_x.timestamp, _x.id, _x.goal, _x.position, _x.error, _x.voltage))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.servo_states is None:
        self.servo_states = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.servo_states = []
      for i in range(0, length):
        val1 = servo_msgs.msg.ServoState()
        _x = val1
        start = end
        end += 28
        (_x.timestamp, _x.id, _x.goal, _x.position, _x.error, _x.voltage,) = _get_struct_d5i().unpack(str[start:end])
        self.servo_states.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.servo_states)
      buff.write(_struct_I.pack(length))
      for val1 in self.servo_states:
        _x = val1
        buff.write(_get_struct_d5i().pack(_x.timestamp, _x.id, _x.goal, _x.position, _x.error, _x.voltage))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.servo_states is None:
        self.servo_states = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.servo_states = []
      for i in range(0, length):
        val1 = servo_msgs.msg.ServoState()
        _x = val1
        start = end
        end += 28
        (_x.timestamp, _x.id, _x.goal, _x.position, _x.error, _x.voltage,) = _get_struct_d5i().unpack(str[start:end])
        self.servo_states.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_d5i = None
def _get_struct_d5i():
    global _struct_d5i
    if _struct_d5i is None:
        _struct_d5i = struct.Struct("<d5i")
    return _struct_d5i
