# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from interfaces/JointsRange.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import interfaces.msg

class JointsRange(genpy.Message):
  _md5sum = "f4756b6cbfe9dd3e05100c20e0ecd197"
  _type = "interfaces/JointsRange"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """interfaces/JointRange joint1
interfaces/JointRange joint2
interfaces/JointRange joint3
interfaces/JointRange joint4
interfaces/JointRange joint5

================================================================================
MSG: interfaces/JointRange
float64 min
float64 max
"""
  __slots__ = ['joint1','joint2','joint3','joint4','joint5']
  _slot_types = ['interfaces/JointRange','interfaces/JointRange','interfaces/JointRange','interfaces/JointRange','interfaces/JointRange']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       joint1,joint2,joint3,joint4,joint5

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(JointsRange, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.joint1 is None:
        self.joint1 = interfaces.msg.JointRange()
      if self.joint2 is None:
        self.joint2 = interfaces.msg.JointRange()
      if self.joint3 is None:
        self.joint3 = interfaces.msg.JointRange()
      if self.joint4 is None:
        self.joint4 = interfaces.msg.JointRange()
      if self.joint5 is None:
        self.joint5 = interfaces.msg.JointRange()
    else:
      self.joint1 = interfaces.msg.JointRange()
      self.joint2 = interfaces.msg.JointRange()
      self.joint3 = interfaces.msg.JointRange()
      self.joint4 = interfaces.msg.JointRange()
      self.joint5 = interfaces.msg.JointRange()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_10d().pack(_x.joint1.min, _x.joint1.max, _x.joint2.min, _x.joint2.max, _x.joint3.min, _x.joint3.max, _x.joint4.min, _x.joint4.max, _x.joint5.min, _x.joint5.max))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.joint1 is None:
        self.joint1 = interfaces.msg.JointRange()
      if self.joint2 is None:
        self.joint2 = interfaces.msg.JointRange()
      if self.joint3 is None:
        self.joint3 = interfaces.msg.JointRange()
      if self.joint4 is None:
        self.joint4 = interfaces.msg.JointRange()
      if self.joint5 is None:
        self.joint5 = interfaces.msg.JointRange()
      end = 0
      _x = self
      start = end
      end += 80
      (_x.joint1.min, _x.joint1.max, _x.joint2.min, _x.joint2.max, _x.joint3.min, _x.joint3.max, _x.joint4.min, _x.joint4.max, _x.joint5.min, _x.joint5.max,) = _get_struct_10d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_10d().pack(_x.joint1.min, _x.joint1.max, _x.joint2.min, _x.joint2.max, _x.joint3.min, _x.joint3.max, _x.joint4.min, _x.joint4.max, _x.joint5.min, _x.joint5.max))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.joint1 is None:
        self.joint1 = interfaces.msg.JointRange()
      if self.joint2 is None:
        self.joint2 = interfaces.msg.JointRange()
      if self.joint3 is None:
        self.joint3 = interfaces.msg.JointRange()
      if self.joint4 is None:
        self.joint4 = interfaces.msg.JointRange()
      if self.joint5 is None:
        self.joint5 = interfaces.msg.JointRange()
      end = 0
      _x = self
      start = end
      end += 80
      (_x.joint1.min, _x.joint1.max, _x.joint2.min, _x.joint2.max, _x.joint3.min, _x.joint3.max, _x.joint4.min, _x.joint4.max, _x.joint5.min, _x.joint5.max,) = _get_struct_10d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_10d = None
def _get_struct_10d():
    global _struct_10d
    if _struct_10d is None:
        _struct_10d = struct.Struct("<10d")
    return _struct_10d
