cmake_minimum_required(VERSION 3.0.2)
project(rk3588s_runtime_navigation)

find_package(catkin REQUIRED)
catkin_package()

catkin_install_python(PROGRAMS scripts/fake_scan_node.py
  DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})
install(DIRECTORY launch config
  DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION})

